//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// You can write your custom code in the chat.component.tns.ts file instead.
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Injector } from '@angular/core';

abstract class CustomEventHandlers {}

@Component({
    templateUrl: './chat.component.html',
    styleUrls: ['./chat.component.css']
})
export abstract class ChatViewBaseComponent extends CustomEventHandlers {
    public $config = {
        chat: {
            botId: '5c12b8dccd56814ee0ef2ec9',
            channelId: '9e11dd6b-6fb8-4bff-97f4-55acad3f4cca',
            channelToken: '5dcabce2-7728-46ab-968a-7d679c64205a'
        }
    };

    constructor(public injector: Injector) {
        super();
    }
}
