//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
export class ClaimsTest {
    public _id: string;
    public name: string;
    public date: Date;
    public vehicle: string;
    public image: string;
    public description: string;
    public policynumber: string;
    public type: string;
}
